import { initializeApp, getApps, getApp } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';
import { getAuth } from 'firebase/auth';

// Safely import or read firebase config
let firebaseConfig;
try {
  // Use config generated by set_up_firebase
  firebaseConfig = {
    projectId: "dogwood-torus-v71nt",
    appId: "1:967038691092:web:fad69deb0535e388814401",
    apiKey: "AIzaSyDefOJLPRU_n7wpJBsHUVMSMJeg6CEK6DY",
    authDomain: "dogwood-torus-v71nt.firebaseapp.com",
    storageBucket: "dogwood-torus-v71nt.firebasestorage.app",
    messagingSenderId: "967038691092"
  };
} catch (e) {
  console.warn("Could not load firebase-applet-config.json:", e);
}

let app;
let db: any = null;
let auth: any = null;

if (firebaseConfig) {
  try {
    app = getApps().length === 0 ? initializeApp(firebaseConfig) : getApp();
    db = getFirestore(app);
    auth = getAuth(app);
  } catch (error) {
    console.error("Failed to initialize Firebase services:", error);
  }
}

export { db, auth };
