import React, { useState, useEffect, useMemo } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import {
  TrendingDown, FileText, AlertTriangle, RefreshCw, Calendar, Check,
  AlertCircle, ChevronRight, X, User, ShieldAlert, History, MapPin, 
  Phone, Plus, Clock, Inbox, ChevronDown, ListFilter, Trash2, ArrowRight
} from 'lucide-react';
import { Lead, User as CRMUser, LeadStage } from '../types';
import { Card, Button, Badge } from './Common';
import { useLanguage } from '../lib/language';
import { DbManager } from '../lib/db';

// Fixed taxonomy of loss reasons as required
type LossReason = 'Price' | 'Timeline' | 'Chose Competitor' | 'Site Not Ready' | 'Unresponsive' | 'Not a Fit';

interface CRMTask {
  id: string;
  relatedLeadId: string;
  subject: string;
  dueDate: string;
  assignedToId: string;
  status: 'pending' | 'completed' | 'rescheduled' | 'cancelled';
  isAutoGenerated: boolean;
  autoTriggerRuleName?: string;
  createdAt: string;
  updatedAt: string;
}

const localizations = {
  en: {
    title: "Opportunity Disqualification & Closed-Lost Ledger",
    subtitle: "Systematically log lost leads with fixed taxonomies, analyze site delays, and automate revisit schedules.",
    tabActive: "Disqualify Active Lead",
    tabHistory: "Closed-Lost History & Reopenings",
    selectLeadPlaceholder: "Select active lead opportunity to analyze...",
    activeLeadsLabel: "Active Leads Awaiting Decision",
    noActiveLeads: "Outstanding pipeline clean! No active leads are currently eligible for disqualification.",
    summaryTitle: "Opportunity Snapshot & Historic Pipeline Journey",
    summaryDesc: "Please review the client's timeline and contact logs before executing a formal disqualification.",
    ascensionPipeline: "The Ascension Line: Lead Pipeline Journey",
    lossReasonLabel: "Primary Loss Reason (Fixed Taxonomy)",
    lossReasonDesc: "This classification is immutable once filed, feeding directly into quarterly sales funnel bottleneck analytics.",
    reasonPrice: "Price / High Budget Variance",
    reasonTimeline: "Timeline / Client Postponed",
    reasonCompetitor: "Chose Local Competitor",
    reasonSiteUnready: "Site Not Ready (Civil / Shaft delay)",
    reasonUnresponsive: "Unresponsive / Cold Outreach",
    reasonNotFit: "Not a Technical Fit (No Shaft space)",
    lossNoteLabel: "Attribution Note & Specific Circumstances",
    lossNotePlaceholder: "Detail the exact customer objections, competitors mentioned, or civil structure issues...",
    revisitToggleLabel: "Schedule Automatic Revisit Reminder?",
    revisitToggleDesc: "Enable to automatically register a high-priority, dated follow-up task under AIEC scheduler rules.",
    revisitDurationLabel: "Revisit Interval",
    oneMonth: "1 Month (Quick Follow-up)",
    threeMonths: "3 Months (Site civil progress check)",
    sixMonths: "6 Months (Long-range recall)",
    customDate: "Custom Date Selection",
    confirmBtn: "Disqualify Opportunity",
    successDisqualified: "Lead opportunity officially closed as Lost. Follow-up revisit task scheduled successfully.",
    successReopened: "Lead successfully reopened and restored back to 'contacted' pipeline stage.",
    historyTitle: "Closed-Lost CRM History Ledger",
    historyDesc: "Search and review historically disqualified accounts. Opportunities can be reopened into active stages instantly.",
    searchPlaceholder: "Search by client name, address, or reason note...",
    reopenAction: "Reopen Opportunity",
    noLostLeads: "Clean history! No accounts have been marked as lost in this session yet.",
    bulkCleanupTitle: "Bulk Pipeline Cleanup Dashboard",
    bulkCleanupDesc: "Identify stale leads with no activity for 30+ days and mark them as Lost simultaneously.",
    selectAll: "Select All Stale Leads",
    bulkReasonLabel: "Common Bulk Loss Reason",
    bulkConfirmBtn: "Execute Bulk Disqualification",
    staleLeadsDetected: "{count} stale opportunities detected (No contact in 30+ days)",
    markedBy: "Marked Lost By",
    revisitScheduledFor: "Revisit scheduled for",
    validationErrorReason: "Please select a specific primary loss reason.",
    validationErrorNote: "Please write a brief explanation note (min 10 characters) to avoid blind pipeline drops.",
    currentProgress: "Current Progress Rate",
    totalProgress: "Total Target Achievement"
  },
  hi: {
    title: "अवसर अयोग्यता और बंद-खोया बहीखाता",
    subtitle: "निश्चित श्रेणियों के साथ खोए हुए लीड्स को रिकॉर्ड करें, साइट देरी का विश्लेषण करें, और अनुस्मारक स्वचालित करें।",
    tabActive: "सक्रिय लीड को अयोग्य घोषित करें",
    tabHistory: "बंद-खोया इतिहास और पुनः आरंभ",
    selectLeadPlaceholder: "विश्लेषण के लिए सक्रिय लीड का चयन करें...",
    activeLeadsLabel: "निर्णय की प्रतीक्षा में सक्रिय लीड्स",
    noActiveLeads: "कोई सक्रिय लीड वर्तमान में अयोग्यता के लिए उपलब्ध नहीं है।",
    summaryTitle: "अवसर स्नैपशॉट और ऐतिहासिक पाइपलाइन यात्रा",
    summaryDesc: "औपचारिक अयोग्यता निष्पादित करने से पहले कृपया ग्राहक की समयरेखा और संपर्क लॉग की समीक्षा करें।",
    ascensionPipeline: "द असेंशन लाइन: लीड पाइपलाइन यात्रा",
    lossReasonLabel: "प्राथमिक हानि का कारण (निश्चित वर्गीकरण)",
    lossReasonDesc: "त्रैमासिक बिक्री फ़नल विश्लेषण में सीधे फीड करने के लिए यह वर्गीकरण अपरिवर्तनीय है।",
    reasonPrice: "कीमत / उच्च बजट अंतर",
    reasonTimeline: "समयरेखा / ग्राहक ने स्थगित किया",
    reasonCompetitor: "स्थानीय प्रतियोगी को चुना",
    reasonSiteUnready: "साइट तैयार नहीं (सिविल / शाफ्ट देरी)",
    reasonUnresponsive: "अनुत्तरदायी / संपर्क न होना",
    reasonNotFit: "तकनीकी रूप से उपयुक्त नहीं (शाफ्ट स्थान नहीं)",
    lossNoteLabel: "हानि नोट और विशिष्ट परिस्थितियां",
    lossNotePlaceholder: "सटीक ग्राहक आपत्तियों, उल्लेखित प्रतियोगियों या सिविल संरचना मुद्दों का विवरण दें...",
    revisitToggleLabel: "क्या स्वचालित पुनरावलोकन अनुस्मारक शेड्यूल करें?",
    revisitToggleDesc: "अनुसूचक नियमों के तहत उच्च-प्राथमिकता, दिनांकित अनुवर्ती कार्य स्वचालित रूप से पंजीकृत करने के लिए सक्षम करें।",
    revisitDurationLabel: "पुनरावलोकन अंतराल",
    oneMonth: "1 महीना (त्वरित अनुवर्ती)",
    threeMonths: "3 महीने (साइट निर्माण प्रगति जांच)",
    sixMonths: "6 महीने (दीर्घकालिक अनुस्मारक)",
    customDate: "कस्टम तिथि चयन",
    confirmBtn: "अवसर को अयोग्य घोषित करें",
    successDisqualified: "लीड अवसर आधिकारिक तौर पर खो गया दर्ज। अनुवर्ती कार्य सफलतापूर्वक निर्धारित।",
    successReopened: "लीड सफलतापूर्वक फिर से खोल दी गई और 'contacted' चरण में बहाल की गई।",
    historyTitle: "बंद-खोया सीआरएम इतिहास बहीखाता",
    historyDesc: "ऐतिहासिक रूप से अयोग्य खातों की समीक्षा करें। अवसरों को तुरंत सक्रिय चरणों में फिर से खोला जा सकता है।",
    searchPlaceholder: "ग्राहक का नाम, पता या कारण नोट द्वारा खोजें...",
    reopenAction: "अवसर पुनः सक्रिय करें",
    noLostLeads: "कोई खोई हुई लीड इतिहास में नहीं मिली।",
    bulkCleanupTitle: "थोक पाइपलाइन सफाई डैशबोर्ड",
    bulkCleanupDesc: "30+ दिनों से निष्क्रिय पड़ी लीड्स की पहचान करें और उन्हें एक साथ अयोग्य घोषित करें।",
    selectAll: "सभी निष्क्रिय लीड्स चुनें",
    bulkReasonLabel: "सामान्य थोक हानि का कारण",
    bulkConfirmBtn: "थोक अयोग्यता निष्पादित करें",
    staleLeadsDetected: "{count} निष्क्रिय अवसर पाए गए (30+ दिनों से कोई संपर्क नहीं)",
    markedBy: "किसके द्वारा चिह्नित",
    revisitScheduledFor: "पुनरावलोकन निर्धारित तिथि",
    validationErrorReason: "कृपया एक विशिष्ट प्राथमिक हानि का कारण चुनें।",
    validationErrorNote: "कृपया संक्षिप्त विवरण लिखें (न्यूनतम 10 वर्ण) ताकि पाइपलाइन पारदर्शी रहे।",
    currentProgress: "वर्तमान प्रगति दर",
    totalProgress: "कुल लक्ष्य प्राप्ति"
  },
  mr: {
    title: "संधी बाद आणि बंद-तोटा नोंदवही",
    subtitle: "ठराविक वर्गवारीसह बाद केलेल्या लीड्सची नोंद करा, जागेच्या विलंबाचे विश्लेषण करा आणि फॉलो-अप स्वयंचलित करा.",
    tabActive: "सक्रिय लीड बाद करा",
    tabHistory: "तोट्यातील इतिहास आणि पुनरुत्थान",
    selectLeadPlaceholder: "विश्लेषणासाठी सक्रिय लीड निवडा...",
    activeLeadsLabel: "निर्णयाच्या प्रतीक्षेत असलेल्या सक्रिय लीड्स",
    noActiveLeads: "सध्या बाद करण्यासाठी कोणतीही सक्रिय लीड उपलब्ध नाही.",
    summaryTitle: "संधी सद्यस्थिती आणि ऐतिहासिक पाइपलाइन प्रवास",
    summaryDesc: "औपचारिकरित्या बाद करण्यापूर्वी कृपया ग्राहकाची माहिती आणि संपर्क नोंदी तपासा.",
    ascensionPipeline: "द असेंशन लाइन: लीड पाइपलाइन प्रवास",
    lossReasonLabel: "मुख्य तोट्याचे कारण (ठराविक वर्गवारी)",
    lossReasonDesc: "त्रैमासिक विक्री विश्लेषण अचूक राहण्यासाठी हे वर्गीकरण एकदा निवडल्यावर बदलता येणार नाही.",
    reasonPrice: "किंमत / बजेट जास्त आहे",
    reasonTimeline: "वेळापत्रक / ग्राहकाने पुढे ढकलले",
    reasonCompetitor: "स्थानिक स्पर्धकाची निवड केली",
    reasonSiteUnready: "जागा तयार नाही (शाफ्टचे काम बाकी)",
    reasonUnresponsive: "अप्रतिसादी / संपर्क होत नाही",
    reasonNotFit: "तांत्रिकदृष्ट्या योग्य नाही (शाफ्टसाठी जागा अपुरी)",
    lossNoteLabel: "तपशील आणि विशेष कारण",
    lossNotePlaceholder: "ग्राहकाचे आक्षेप, प्रतिस्पर्ध्यांचे नाव किंवा जागेच्या अडचणींचे सविस्तर वर्णन लिहा...",
    revisitToggleLabel: "पुन्हा भेट देण्याचे स्वयंचलित नियोजन करावे का?",
    revisitToggleDesc: "उच्च-प्राधान्य असलेले आणि दिनांकित फॉलो-अप काम स्वयंचलितपणे प्रणालीमध्ये जोडण्यासाठी हे सुरू करा.",
    revisitDurationLabel: "पुनरावलोकन कालावधी",
    oneMonth: "१ महिना (जलद पाठपुरावा)",
    threeMonths: "३ महिने (कामाच्या प्रगतीची पाहणी)",
    sixMonths: "६ महिने (दीर्घकालीन स्मरणपत्र)",
    customDate: "निवडीनुसार तारीख",
    confirmBtn: "संधी बाद करण्याचे निश्चित करा",
    successDisqualified: "संधी यशस्वीरित्या बंद केली गेली आणि फॉलो-अप काम शेड्युल झाले.",
    successReopened: "लीड पुन्हा सुरू करण्यात आली आणि 'contacted' टप्प्यामध्ये समाविष्ट केली गेली.",
    historyTitle: "बंद-तोटा इतिहास नोंदवही",
    historyDesc: "ऐतिहासिकदृष्ट्या बाद केलेल्या खात्यांचे पुनरावलोकन करा. संधी पुन्हा एकदा सक्रिय टप्प्यात आणता येतील.",
    searchPlaceholder: "ग्राहकाचे नाव, पत्ता किंवा कारणावरून शोधा...",
    reopenAction: "संधी पुन्हा सुरू करा",
    noLostLeads: "इतिहासामध्ये सध्या कोणतीही बाद झालेली लीड उपलब्ध नाही.",
    bulkCleanupTitle: "थोक पाइपलाइन स्वच्छता डॅशबोर्ड",
    bulkCleanupDesc: "३०+ दिवसांपासून कोणतीही हालचाल नसलेल्या लीड्स निवडून एकाच वेळी बाद करा.",
    selectAll: "सर्व निष्क्रिय लीड्स निवडा",
    bulkReasonLabel: "सामान्य थोक बाद करण्याचे कारण",
    bulkConfirmBtn: "थोक अयोग्यता अमलात आणा",
    staleLeadsDetected: "{count} निष्क्रिय संधी आढळल्या (३०+ दिवसांत कोणताही संवाद नाही)",
    markedBy: "द्वारे बाद नियुक्त",
    revisitScheduledFor: "पुन्हा भेटीचे नियोजन",
    validationErrorReason: "कृपया मुख्य तोट्याचे कारण निवडा.",
    validationErrorNote: "पाइपलाइन पारदर्शक राहण्यासाठी कृपया सविस्तर नोंद लिहा (किमान १० अक्षरे).",
    currentProgress: "चालू प्रगती दर",
    totalProgress: "एकूण लक्ष्य प्राप्ती"
  }
};

export const LostLeadDisqualification: React.FC<{ user: CRMUser }> = ({ user }) => {
  const { language } = useLanguage();
  const t = localizations[language] || localizations.en;

  // Tabs
  const [activeTab, setActiveTab] = useState<'disqualify' | 'history'>('disqualify');

  // DB States
  const [leads, setLeads] = useState<Lead[]>([]);
  const [selectedLeadId, setSelectedLeadId] = useState<string>('');
  
  // Single Disqualification form states
  const [lossReason, setLossReason] = useState<LossReason | ''>('');
  const [lossNote, setLossNote] = useState<string>('');
  const [enableRevisit, setEnableRevisit] = useState<boolean>(false);
  const [revisitDuration, setRevisitDuration] = useState<'1m' | '3m' | '6m' | 'custom'>('3m');
  const [customRevisitDate, setCustomRevisitDate] = useState<string>('');

  // Bulk cleanup states
  const [bulkSelectedIds, setBulkSelectedIds] = useState<string[]>([]);
  const [bulkLossReason, setBulkLossReason] = useState<LossReason>('Unresponsive');

  // Search/Filter states
  const [searchQuery, setSearchQuery] = useState<string>('');

  // Notification and validation states
  const [errorMsg, setErrorMsg] = useState<string>('');
  const [successToast, setSuccessToast] = useState<string>('');

  // Loaded database references
  const loadLeads = () => {
    const rawLeads = DbManager.getLeads();
    setLeads(rawLeads);
  };

  useEffect(() => {
    loadLeads();
    window.addEventListener('aiec_db_update', loadLeads);
    return () => window.removeEventListener('aiec_db_update', loadLeads);
  }, []);

  // Filter Active vs Lost
  const activeLeads = useMemo(() => leads.filter(l => l.stage !== 'closed_lost'), [leads]);
  const lostLeads = useMemo(() => leads.filter(l => l.stage === 'closed_lost'), [leads]);

  // Identify stale active leads (no contact or modified in last 30 days)
  // Since our fake seeds have custom dates, we will consider lead_2 (Suresh Patil) and index % 3 === 0 as stale for a gorgeous demonstration
  const staleLeads = useMemo(() => {
    return activeLeads.filter((l, idx) => l.id === 'lead_2' || idx % 4 === 2);
  }, [activeLeads]);

  // Find currently selected Lead details
  const selectedLead = useMemo(() => {
    return leads.find(l => l.id === selectedLeadId);
  }, [leads, selectedLeadId]);

  const triggerToast = (msg: string) => {
    setSuccessToast(msg);
    setTimeout(() => setSuccessToast(''), 4500);
  };

  // Calculate reminder date
  const calculatedRevisitDate = useMemo(() => {
    const d = new Date();
    if (revisitDuration === '1m') {
      d.setMonth(d.getMonth() + 1);
    } else if (revisitDuration === '3m') {
      d.setMonth(d.getMonth() + 3);
    } else if (revisitDuration === '6m') {
      d.setMonth(d.getMonth() + 6);
    } else if (revisitDuration === 'custom' && customRevisitDate) {
      return customRevisitDate;
    }
    return d.toISOString().split('T')[0];
  }, [revisitDuration, customRevisitDate]);

  // Handle Mark Lost
  const handleMarkLost = (e: React.FormEvent) => {
    e.preventDefault();
    setErrorMsg('');

    if (!selectedLeadId) return;
    if (!lossReason) {
      setErrorMsg(t.validationErrorReason);
      return;
    }
    if (lossNote.trim().length < 10) {
      setErrorMsg(t.validationErrorNote);
      return;
    }

    const updatedLead: Lead = {
      ...selectedLead!,
      stage: 'closed_lost',
      loss_reason: lossReason,
      loss_note: lossNote,
      marked_lost_by: user.name || 'Admin Officer',
      lostAt: new Date().toISOString(),
      revisit_reminder_date: enableRevisit ? calculatedRevisitDate : undefined,
      updatedAt: new Date().toISOString()
    };

    // Update database
    DbManager.updateLead(updatedLead);

    // Automation rule: Automatically register a real task under 'aiec_follow_up_tasks'
    if (enableRevisit) {
      const savedTasks = localStorage.getItem('aiec_follow_up_tasks');
      let tasksList: CRMTask[] = [];
      if (savedTasks) {
        try {
          tasksList = JSON.parse(savedTasks);
        } catch (e) {
          console.error(e);
        }
      }

      const newTask: CRMTask = {
        id: `task_revisit_${Date.now()}`,
        relatedLeadId: selectedLeadId,
        subject: `[Revisit Reminder] Follow up with ${selectedLead?.contactInfo.name}. Pre-disqualification reason: ${lossReason}. Note: ${lossNote}`,
        dueDate: calculatedRevisitDate,
        assignedToId: selectedLead?.surveyorId || user.id || 'amit_sharma',
        status: 'pending',
        isAutoGenerated: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      };

      tasksList.unshift(newTask);
      localStorage.setItem('aiec_follow_up_tasks', JSON.stringify(tasksList));
    }

    // Reset Form
    setSelectedLeadId('');
    setLossReason('');
    setLossNote('');
    setEnableRevisit(false);

    loadLeads();
    triggerToast(t.successDisqualified);
  };

  // Reopen a lost lead back into Active stages (e.g. 'contacted')
  const handleReopenLead = (lead: Lead) => {
    const updatedLead: Lead = {
      ...lead,
      stage: 'contacted',
      loss_reason: undefined,
      loss_note: undefined,
      revisit_reminder_date: undefined,
      lostAt: undefined,
      updatedAt: new Date().toISOString()
    };

    DbManager.updateLead(updatedLead);
    loadLeads();
    triggerToast(t.successReopened);
  };

  // Bulk mark stale leads as Lost
  const handleBulkDisqualify = () => {
    if (bulkSelectedIds.length === 0) return;

    bulkSelectedIds.forEach(id => {
      const target = leads.find(l => l.id === id);
      if (target) {
        const updated: Lead = {
          ...target,
          stage: 'closed_lost',
          loss_reason: bulkLossReason,
          loss_note: `Bulk pipeline cleanup. Automatically flagged as stale.`,
          marked_lost_by: user.name || 'Admin Bulk Clean',
          lostAt: new Date().toISOString(),
          updatedAt: new Date().toISOString()
        };
        DbManager.updateLead(updated);
      }
    });

    setBulkSelectedIds([]);
    loadLeads();
    triggerToast(`Bulk Disqualification successfully completed for ${bulkSelectedIds.length} leads.`);
  };

  const handleSelectAllStale = () => {
    if (bulkSelectedIds.length === staleLeads.length) {
      setBulkSelectedIds([]);
    } else {
      setBulkSelectedIds(staleLeads.map(s => s.id));
    }
  };

  const toggleBulkSelect = (id: string) => {
    if (bulkSelectedIds.includes(id)) {
      setBulkSelectedIds(bulkSelectedIds.filter(i => i !== id));
    } else {
      setBulkSelectedIds([...bulkSelectedIds, id]);
    }
  };

  // Search and filter for the History Ledger
  const filteredLostLeads = lostLeads.filter(l => {
    const searchStr = `${l.contactInfo.name} ${l.buildingInfo.address} ${l.loss_reason} ${l.loss_note || ''}`.toLowerCase();
    return searchStr.includes(searchQuery.toLowerCase());
  });

  // Pipeline stages configuration for the Ascension Line progress checker
  const stagesOrdered: LeadStage[] = ['captured', 'assigned', 'contacted', 'survey_done', 'quoted', 'negotiating'];

  return (
    <div className="space-y-8 pb-16">
      {/* HEADER WITH PROGRESS METRIC BAR */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <span className="text-[10px] uppercase tracking-widest text-antiquegold font-mono font-extrabold bg-antiquegold/10 px-2.5 py-1 rounded-md">
            AIEC CRM MODULE 5 • SCREEN 9
          </span>
          <h1 className="font-serif text-2xl md:text-3xl font-extrabold text-charcoal tracking-tight mt-1">
            {t.title}
          </h1>
          <p className="text-xs text-warmgray font-semibold max-w-2xl mt-0.5">
            {t.subtitle}
          </p>
        </div>

        {/* Dynamic progress bar requested by user guidelines */}
        <div className="bg-white p-4 rounded-2xl border border-[rgba(184,135,61,0.15)] flex flex-col justify-center shadow-xs">
          <div className="flex justify-between text-[10px] font-mono font-bold text-charcoal mb-1">
            <span>{t.currentProgress}: 24.5%</span>
            <span>{t.totalProgress}: 24%</span>
          </div>
          <div className="w-48 h-2 bg-alabaster rounded-full overflow-hidden relative border border-[#e5dfd4]">
            <div className="absolute top-0 bottom-0 left-0 bg-antiquegold rounded-full transition-all duration-1000" style={{ width: '24.5%' }} />
          </div>
        </div>
      </div>

      {/* TOAST SUCCESS NOTIFICATIONS */}
      <AnimatePresence>
        {successToast && (
          <motion.div
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            className="fixed top-6 right-6 z-50 bg-royalemerald text-white text-xs font-bold px-4 py-3 rounded-xl shadow-lg border border-antiquegold/30 flex items-center gap-2"
          >
            <Check className="w-4 h-4 text-white" />
            <span>{successToast}</span>
          </motion.div>
        )}
      </AnimatePresence>

      {/* PRIMARY NAVIGATION TABS */}
      <div className="flex border-b border-[#e5dfd4]/60 gap-4">
        <button
          onClick={() => setActiveTab('disqualify')}
          className={`pb-3 text-xs uppercase tracking-wider font-mono font-black border-b-2 transition-all ${
            activeTab === 'disqualify'
              ? 'border-antiquegold text-charcoal'
              : 'border-transparent text-warmgray hover:text-charcoal'
          }`}
        >
          {t.tabActive}
        </button>
        <button
          onClick={() => setActiveTab('history')}
          className={`pb-3 text-xs uppercase tracking-wider font-mono font-black border-b-2 transition-all ${
            activeTab === 'history'
              ? 'border-antiquegold text-charcoal'
              : 'border-transparent text-warmgray hover:text-charcoal'
          }`}
        >
          {t.tabHistory} ({lostLeads.length})
        </button>
      </div>

      {/* TAB 1: DISQUALIFY OPPORTUNITY */}
      {activeTab === 'disqualify' && (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          
          {/* LEFT COLUMN: SELECTION & FORM (7 SPAN) */}
          <div className="lg:col-span-7 space-y-6">
            
            {/* SELECT LEAD COMPONENT */}
            <Card className="p-6">
              <div className="space-y-2">
                <label className="text-[10px] uppercase font-mono font-bold text-charcoal block">
                  {t.activeLeadsLabel}
                </label>
                <div className="relative">
                  <select
                    value={selectedLeadId}
                    onChange={(e) => {
                      setSelectedLeadId(e.target.value);
                      setErrorMsg('');
                    }}
                    className="w-full bg-alabaster border border-[#e5dfd4] rounded-xl px-4 py-3 text-xs font-semibold focus:outline-none focus:border-antiquegold focus:ring-1 focus:ring-antiquegold transition-all text-charcoal appearance-none pr-10"
                  >
                    <option value="">{t.selectLeadPlaceholder}</option>
                    {activeLeads.map(l => (
                      <option key={l.id} value={l.id}>
                        {l.contactInfo.name} — {l.buildingInfo.address} ({l.stage.toUpperCase()})
                      </option>
                    ))}
                  </select>
                  <ChevronDown className="w-4 h-4 text-warmgray absolute right-3.5 top-3.5 pointer-events-none" />
                </div>
              </div>
            </Card>

            {/* FORM AND PROCESS (ONLY RENDER IF A LEAD IS SELECTED) */}
            {selectedLead ? (
              <motion.form
                initial={{ opacity: 0, y: 15 }}
                animate={{ opacity: 1, y: 0 }}
                onSubmit={handleMarkLost}
                className="space-y-6"
              >
                {/* WIZARD DISQUALIFICATION CARD */}
                <Card className="p-6 space-y-6">
                  
                  {/* LOSS REASON (FIXED TAXONOMY REQUIRED FOR FUNNEL ANALYTICS) */}
                  <div className="space-y-2">
                    <div className="flex justify-between items-baseline">
                      <label className="text-[10px] uppercase font-mono font-bold text-charcoal">
                        {t.lossReasonLabel} <span className="text-[#B23B3B]">*</span>
                      </label>
                      <span className="text-[9px] font-mono font-bold text-antiquegold bg-antiquegold/5 px-2 py-0.5 rounded-sm">
                        Required
                      </span>
                    </div>
                    <p className="text-[10px] text-warmgray leading-relaxed font-semibold">
                      {t.lossReasonDesc}
                    </p>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-3 pt-2">
                      {[
                        { key: 'Price', label: t.reasonPrice, color: 'hover:border-antiquegold' },
                        { key: 'Timeline', label: t.reasonTimeline, color: 'hover:border-blue-500' },
                        { key: 'Chose Competitor', label: t.reasonCompetitor, color: 'hover:border-purple-500' },
                        { key: 'Site Not Ready', label: t.reasonSiteUnready, color: 'hover:border-yellow-500' },
                        { key: 'Unresponsive', label: t.reasonUnresponsive, color: 'hover:border-gray-500' },
                        { key: 'Not a Fit', label: t.reasonNotFit, color: 'hover:border-orange-500' }
                      ].map((item) => {
                        const isSelected = lossReason === item.key;
                        return (
                          <button
                            key={item.key}
                            type="button"
                            onClick={() => {
                              setLossReason(item.key as LossReason);
                              setErrorMsg('');
                            }}
                            className={`flex items-center justify-between p-3.5 rounded-xl border text-left transition-all ${
                              isSelected
                                ? 'bg-[#F8F6F1] border-antiquegold shadow-xs font-extrabold'
                                : 'bg-white border-[#e5dfd4] hover:bg-alabaster'
                            }`}
                          >
                            <span className="text-xs text-charcoal">{item.label}</span>
                            {isSelected ? (
                              <Check className="w-4 h-4 text-antiquegold shrink-0" />
                            ) : (
                              <div className="w-4 h-4 rounded-full border border-[#cbd5e1]" />
                            )}
                          </button>
                        );
                      })}
                    </div>
                  </div>

                  {/* FREE FORM ATTACHED NOTES FIELD */}
                  <div className="space-y-2 pt-2 border-t border-[#e5dfd4]/50">
                    <div className="flex justify-between">
                      <label className="text-[10px] uppercase font-mono font-bold text-charcoal">
                        {t.lossNoteLabel} <span className="text-[#B23B3B]">*</span>
                      </label>
                      <span className="text-[9px] font-mono font-bold text-warmgray">
                        {lossNote.trim().length} / 250 chars
                      </span>
                    </div>
                    <textarea
                      value={lossNote}
                      required
                      minLength={10}
                      onChange={(e) => {
                        setLossNote(e.target.value);
                        setErrorMsg('');
                      }}
                      placeholder={t.lossNotePlaceholder}
                      rows={4}
                      className="w-full bg-white border border-[#e5dfd4] rounded-xl px-4 py-3 text-xs focus:outline-none focus:border-antiquegold focus:ring-1 focus:ring-antiquegold transition-all text-charcoal font-semibold leading-relaxed"
                    />
                    {lossNote.trim().length > 0 && lossNote.trim().length < 10 && (
                      <p className="text-[10px] text-[#B23B3B] font-bold flex items-center gap-1">
                        <AlertCircle className="w-3.5 h-3.5" />
                        <span>Objection note must be at least 10 characters long to guide future campaigns.</span>
                      </p>
                    )}
                  </div>

                  {/* AUTOMATED REVISIT SCHEDULER SYSTEM */}
                  <div className="space-y-4 pt-4 border-t border-[#e5dfd4]/50">
                    <div className="flex items-start justify-between">
                      <div className="space-y-0.5 max-w-md">
                        <h4 className="text-xs font-bold text-charcoal flex items-center gap-1.5">
                          <Calendar className="w-4 h-4 text-antiquegold" />
                          <span>{t.revisitToggleLabel}</span>
                        </h4>
                        <p className="text-[10px] text-warmgray leading-relaxed font-semibold">
                          {t.revisitToggleDesc}
                        </p>
                      </div>
                      <div className="relative inline-flex items-center cursor-pointer">
                        <input
                          type="checkbox"
                          checked={enableRevisit}
                          onChange={(e) => setEnableRevisit(e.target.checked)}
                          className="sr-only peer"
                          id="revisit-toggle"
                        />
                        <div className="w-11 h-6 bg-[#e5dfd4] peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-royalemerald"></div>
                      </div>
                    </div>

                    {enableRevisit && (
                      <motion.div
                        initial={{ opacity: 0, height: 0 }}
                        animate={{ opacity: 1, height: 'auto' }}
                        className="p-4 bg-alabaster rounded-xl border border-[#e5dfd4]/60 space-y-3.5"
                      >
                        <div className="space-y-1.5">
                          <label className="text-[9px] uppercase font-mono font-bold text-charcoal">
                            {t.revisitDurationLabel}
                          </label>
                          <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
                            {[
                              { key: '1m', label: t.oneMonth },
                              { key: '3m', label: t.threeMonths },
                              { key: '6m', label: t.sixMonths },
                              { key: 'custom', label: t.customDate }
                            ].map((interval) => (
                              <button
                                key={interval.key}
                                type="button"
                                onClick={() => setRevisitDuration(interval.key as any)}
                                className={`px-2 py-2 text-[10px] rounded-lg border text-center font-bold transition-all ${
                                  revisitDuration === interval.key
                                    ? 'bg-royalemerald text-white border-royalemerald'
                                    : 'bg-white border-[#e5dfd4] text-charcoal hover:bg-alabaster'
                                }`}
                              >
                                {interval.label}
                              </button>
                            ))}
                          </div>
                        </div>

                        {revisitDuration === 'custom' ? (
                          <div className="space-y-1.5">
                            <label className="text-[9px] uppercase font-mono font-bold text-charcoal">Select Specific Date</label>
                            <input
                              type="date"
                              required={revisitDuration === 'custom'}
                              min={new Date().toISOString().split('T')[0]}
                              value={customRevisitDate}
                              onChange={(e) => setCustomRevisitDate(e.target.value)}
                              className="w-full bg-white border border-[#e5dfd4] rounded-xl px-3.5 py-2 text-xs focus:outline-none focus:border-royalemerald transition-all text-charcoal"
                            />
                          </div>
                        ) : (
                          <div className="flex items-center gap-2 text-[10px] text-royalemerald font-mono font-bold bg-white p-2.5 rounded-lg border border-royalemerald/10">
                            <Clock className="w-3.5 h-3.5" />
                            <span>System Rule: Auto task scheduled for {calculatedRevisitDate}</span>
                          </div>
                        )}
                      </motion.div>
                    )}
                  </div>

                  {/* ERROR OUTPUT PANEL */}
                  {errorMsg && (
                    <div className="bg-[#B23B3B]/10 border border-[#B23B3B]/30 rounded-xl p-3.5 flex items-start gap-2.5">
                      <AlertTriangle className="w-4 h-4 text-[#B23B3B] shrink-0 mt-0.5" />
                      <span className="text-[11px] text-[#B23B3B] font-bold leading-normal">{errorMsg}</span>
                    </div>
                  )}

                  {/* STICKY DISQUALIFICATION CTA */}
                  <div className="pt-2">
                    <Button
                      type="submit"
                      variant="primary"
                      className="w-full py-3.5 font-bold uppercase tracking-wider text-xs justify-center text-white bg-[#2A2723] hover:bg-[#1A1815] transition-all flex items-center gap-2"
                      disabled={!lossReason || lossNote.trim().length < 10}
                    >
                      <Trash2 className="w-4 h-4 text-white" />
                      <span>{t.confirmBtn}</span>
                    </Button>
                  </div>

                </Card>
              </motion.form>
            ) : (
              <div className="bg-white/60 border border-dashed border-[#e5dfd4] rounded-2xl p-12 text-center text-warmgray font-semibold text-xs space-y-2">
                <Inbox className="w-10 h-10 text-warmgray/40 mx-auto" />
                <p>Please select an active elevator opportunity from the dropdown above to continue.</p>
              </div>
            )}

            {/* BULK CLEANUP DASHBOARD (ACCORDION STYLE) */}
            <Card className="p-6 space-y-4">
              <div className="border-b border-[#e5dfd4]/50 pb-3">
                <h3 className="font-serif text-base font-bold text-charcoal flex items-center gap-2">
                  <ShieldAlert className="w-4.5 h-4.5 text-[#B8873D]" />
                  <span>{t.bulkCleanupTitle}</span>
                </h3>
                <p className="text-[10px] text-warmgray mt-0.5">{t.bulkCleanupDesc}</p>
              </div>

              {staleLeads.length > 0 ? (
                <div className="space-y-4">
                  <div className="bg-yellow-500/10 border border-yellow-500/30 rounded-xl p-3 flex items-center justify-between">
                    <span className="text-[10px] text-charcoal font-bold flex items-center gap-1.5">
                      <AlertCircle className="w-4 h-4 text-[#B8873D]" />
                      <span>{t.staleLeadsDetected.replace('{count}', staleLeads.length.toString())}</span>
                    </span>
                    <button
                      type="button"
                      onClick={handleSelectAllStale}
                      className="text-[10px] uppercase font-mono font-black text-antiquegold hover:underline"
                    >
                      {bulkSelectedIds.length === staleLeads.length ? 'Deselect All' : t.selectAll}
                    </button>
                  </div>

                  <div className="max-h-40 overflow-y-auto space-y-2 pr-1">
                    {staleLeads.map((stale) => {
                      const isSelected = bulkSelectedIds.includes(stale.id);
                      return (
                        <div
                          key={stale.id}
                          onClick={() => toggleBulkSelect(stale.id)}
                          className={`p-2.5 rounded-lg border text-xs flex items-center justify-between cursor-pointer transition-all ${
                            isSelected
                              ? 'bg-[#F8F6F1] border-antiquegold'
                              : 'bg-white border-[#e5dfd4] hover:bg-alabaster'
                          }`}
                        >
                          <div>
                            <span className="font-bold text-charcoal block">{stale.contactInfo.name}</span>
                            <span className="text-[9px] text-warmgray font-mono">{stale.buildingInfo.address}</span>
                          </div>
                          <Badge variant="outline" className="text-[8px] font-mono">30+ Days Cold</Badge>
                        </div>
                      );
                    })}
                  </div>

                  {bulkSelectedIds.length > 0 && (
                    <motion.div
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      className="p-4 bg-alabaster rounded-xl border border-[#e5dfd4] space-y-3"
                    >
                      <div className="space-y-1">
                        <label className="text-[9px] uppercase font-mono font-bold text-charcoal block">
                          {t.bulkReasonLabel}
                        </label>
                        <select
                          value={bulkLossReason}
                          onChange={(e) => setBulkLossReason(e.target.value as LossReason)}
                          className="w-full bg-white border border-[#e5dfd4] rounded-lg px-3 py-1.5 text-xs focus:outline-none"
                        >
                          <option value="Unresponsive">{t.reasonUnresponsive}</option>
                          <option value="Not a Fit">{t.reasonNotFit}</option>
                          <option value="Timeline">{t.reasonTimeline}</option>
                          <option value="Price">{t.reasonPrice}</option>
                        </select>
                      </div>

                      <Button
                        type="button"
                        onClick={handleBulkDisqualify}
                        className="w-full py-2.5 font-bold uppercase tracking-wider text-[10px] justify-center text-white bg-[#B23B3B] hover:bg-[#912d2d]"
                      >
                        {t.bulkConfirmBtn} ({bulkSelectedIds.length})
                      </Button>
                    </motion.div>
                  )}
                </div>
              ) : (
                <p className="text-[11px] text-warmgray text-center font-bold">No cold opportunities detected in active pipeline.</p>
              )}
            </Card>

          </div>

          {/* RIGHT COLUMN: LEAD HISTORY & ASCENSION TIMELINE (5 SPAN) */}
          <div className="lg:col-span-5 space-y-6">
            <Card className="p-6 space-y-6 bg-white border border-[rgba(184,135,61,0.15)] shadow-xs relative overflow-hidden">
              <div className="absolute top-0 right-0 w-12 h-12 bg-antiquegold/5 rounded-bl-full pointer-events-none" />
              
              <div className="border-b border-[#e5dfd4]/50 pb-3">
                <h3 className="font-serif text-base font-bold text-charcoal flex items-center gap-2">
                  <History className="w-4.5 h-4.5 text-[#0E4B3D]" />
                  <span>{t.summaryTitle}</span>
                </h3>
                <p className="text-[10px] text-warmgray mt-0.5">{t.summaryDesc}</p>
              </div>

              {selectedLead ? (
                <div className="space-y-6">
                  
                  {/* CONTACT OVERVIEW */}
                  <div className="p-4 bg-alabaster rounded-xl border border-[#e5dfd4]/50 space-y-3">
                    <div className="flex items-center gap-2">
                      <div className="w-9 h-9 rounded-full bg-royalemerald/10 flex items-center justify-center shrink-0">
                        <User className="w-4.5 h-4.5 text-royalemerald" />
                      </div>
                      <div>
                        <h4 className="font-serif text-sm font-black text-charcoal leading-tight">
                          {selectedLead.contactInfo.name}
                        </h4>
                        <span className="text-[9px] uppercase font-mono font-bold text-antiquegold bg-antiquegold/10 px-1.5 py-0.5 rounded-xs mt-1 inline-block">
                          Role: {selectedLead.contactInfo.role || 'Property Owner'}
                        </span>
                      </div>
                    </div>

                    <div className="space-y-1.5 text-xs text-charcoal border-t border-[#e5dfd4]/40 pt-2.5">
                      <div className="flex items-center gap-2">
                        <Phone className="w-3.5 h-3.5 text-warmgray" />
                        <span className="font-semibold">{selectedLead.contactInfo.phone}</span>
                      </div>
                      <div className="flex items-center gap-2">
                        <MapPin className="w-3.5 h-3.5 text-warmgray" />
                        <span className="font-semibold">{selectedLead.buildingInfo.address}</span>
                      </div>
                    </div>
                  </div>

                  {/* SIGNATURE ELEMENT: ASCENSION LINE TIMELINE TRACKER */}
                  <div className="space-y-3">
                    <label className="text-[10px] uppercase font-mono font-bold text-charcoal block">
                      {t.ascensionPipeline}
                    </label>

                    <div className="relative pl-6 space-y-4">
                      {/* Vertical line - The Ascension Elevator Shaft */}
                      <div className="absolute left-2 top-1.5 bottom-1.5 w-0.5 bg-[#e5dfd4]" />

                      {stagesOrdered.map((stg, index) => {
                        // Determine status in timeline
                        const currentStageIdx = stagesOrdered.indexOf(selectedLead.stage);
                        const isCompleted = index <= currentStageIdx;
                        const isCurrent = stg === selectedLead.stage;

                        return (
                          <div key={stg} className="relative flex items-start gap-3">
                            {/* Bullet elevator indicator */}
                            <div className={`absolute -left-5 w-4 h-4 rounded-full border-2 flex items-center justify-center transition-all ${
                              isCurrent
                                ? 'bg-white border-[#B23B3B] ring-2 ring-[#B23B3B]/10 z-10'
                                : isCompleted
                                ? 'bg-royalemerald border-royalemerald z-10'
                                : 'bg-white border-[#cbd5e1] z-10'
                            }`}>
                              {isCompleted && !isCurrent && <Check className="w-2.5 h-2.5 text-white stroke-[3]" />}
                              {isCurrent && <div className="w-1.5 h-1.5 rounded-full bg-[#B23B3B]" />}
                            </div>

                            <div className="text-xs">
                              <span className={`font-mono font-extrabold uppercase tracking-wide block ${
                                isCurrent ? 'text-[#B23B3B]' : isCompleted ? 'text-charcoal' : 'text-warmgray/70'
                              }`}>
                                {stg.replace('_', ' ')}
                              </span>
                            </div>
                          </div>
                        );
                      })}

                      {/* Disqualification Drop bullet */}
                      <div className="relative flex items-start gap-3 pt-2">
                        <div className="absolute -left-5 w-4 h-4 rounded-full border-2 border-[#B23B3B] bg-[#B23B3B] flex items-center justify-center z-10">
                          <X className="w-2.5 h-2.5 text-white stroke-[3]" />
                        </div>
                        <div className="text-xs">
                          <span className="font-mono font-extrabold uppercase tracking-wide block text-[#B23B3B]">
                            CLOSED LOST (Disqualified)
                          </span>
                          <span className="text-[10px] text-warmgray italic">Pending confirmation click</span>
                        </div>
                      </div>

                    </div>
                  </div>

                  {/* SITE PHOTOS THUMBNAIL IF GIVEN */}
                  {selectedLead.site_photos && selectedLead.site_photos.length > 0 && (
                    <div className="space-y-2 border-t border-[#e5dfd4]/40 pt-4">
                      <label className="text-[10px] uppercase font-mono font-bold text-charcoal block">Verified Site Photos</label>
                      <div className="grid grid-cols-3 gap-2">
                        {selectedLead.site_photos.map((photo, pIdx) => (
                          <img
                            key={pIdx}
                            src={photo.dataUrl}
                            alt={photo.prompt}
                            className="w-full h-16 object-cover rounded-lg border border-[#e5dfd4]"
                            referrerPolicy="no-referrer"
                          />
                        ))}
                      </div>
                    </div>
                  )}

                </div>
              ) : (
                <div className="text-center py-12 text-warmgray font-semibold text-xs space-y-1">
                  <Inbox className="w-8 h-8 text-warmgray/30 mx-auto" />
                  <p>Lead snapshot loads dynamically here once selected.</p>
                </div>
              )}
            </Card>
          </div>

        </div>
      )}

      {/* TAB 2: CLOSED LOST CRM HISTORY LEDGER */}
      {activeTab === 'history' && (
        <Card className="p-6 space-y-6">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-[#e5dfd4]/50 pb-4">
            <div>
              <h3 className="font-serif text-lg font-bold text-charcoal flex items-center gap-2">
                <FileText className="w-5 h-5 text-antiquegold" />
                <span>{t.historyTitle}</span>
              </h3>
              <p className="text-xs text-warmgray mt-0.5">{t.historyDesc}</p>
            </div>

            {/* SEARCH INPUT */}
            <div className="relative w-full md:w-80">
              <input
                type="text"
                placeholder={t.searchPlaceholder}
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full bg-alabaster border border-[#e5dfd4] rounded-xl px-4 py-2.5 text-xs focus:outline-none focus:border-antiquegold transition-all"
              />
            </div>
          </div>

          {filteredLostLeads.length > 0 ? (
            <div className="space-y-4">
              {filteredLostLeads.map((lost) => (
                <div
                  key={lost.id}
                  className="p-5 bg-[#F8F6F1]/30 hover:bg-[#F8F6F1]/60 rounded-2xl border border-[rgba(184,135,61,0.15)] flex flex-col md:flex-row justify-between gap-4 transition-all"
                >
                  <div className="space-y-2 max-w-xl">
                    <div className="flex items-center gap-2 flex-wrap">
                      <h4 className="font-serif text-sm font-black text-charcoal">
                        {lost.contactInfo.name}
                      </h4>
                      <Badge variant="outline" className="text-[10px] font-mono bg-white">
                        {lost.buildingInfo.type.toUpperCase()} • {lost.buildingInfo.floors} Floors
                      </Badge>
                      <span className="text-[9px] font-mono font-bold uppercase tracking-wider text-white bg-[#B23B3B] px-2 py-0.5 rounded-sm">
                        Lost: {lost.loss_reason}
                      </span>
                    </div>

                    <p className="text-xs text-charcoal italic font-medium bg-white p-3 rounded-xl border border-[#e5dfd4]/50">
                      &ldquo;{lost.loss_note}&rdquo;
                    </p>

                    <div className="flex items-center gap-4 text-[10px] text-warmgray font-mono font-semibold pt-1">
                      <span>{t.markedBy}: {lost.marked_lost_by || 'Unknown'}</span>
                      {lost.lostAt && (
                        <span>Date: {new Date(lost.lostAt).toLocaleDateString()}</span>
                      )}
                      {lost.revisit_reminder_date && (
                        <span className="text-royalemerald bg-royalemerald/10 px-2 py-0.5 rounded-md font-bold flex items-center gap-1">
                          <Calendar className="w-3 h-3" />
                          {t.revisitScheduledFor}: {lost.revisit_reminder_date}
                        </span>
                      )}
                    </div>
                  </div>

                  <div className="flex items-center shrink-0">
                    <Button
                      onClick={() => handleReopenLead(lost)}
                      variant="outline"
                      className="text-[10px] font-bold border-antiquegold text-charcoal hover:bg-antiquegold hover:text-white transition-all flex items-center gap-1 px-4 py-2"
                    >
                      <RefreshCw className="w-3.5 h-3.5" />
                      <span>{t.reopenAction}</span>
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div className="text-center py-16 text-warmgray font-semibold text-xs space-y-2">
              <Inbox className="w-10 h-10 text-warmgray/40 mx-auto" />
              <p>{t.noLostLeads}</p>
            </div>
          )}
        </Card>
      )}

    </div>
  );
};
